# Site settings
title: Titas K.
email: underconstruction@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://titask.github.io" # the base hostname & protocol for your site
twitter_username: notwitter
github_username:  titask

plugins:
    - jekyll-remote-theme

# Build settings
markdown: kramdown
#remote_theme: benbalter/retlab
remote_theme: poole/hyde
